Kevin async question verify notifications
ubco-db/office-hours pull request #106
Opened 2024-03-06 23:57 UTC by wskksw

# Description

1. allow students to determine whether they want to escalate questions
2. Render Async questions of different status with different UI
3. Differentiate Async question status further
4. Document logic of new async question feature

Bug fixes/improvements:
1. add taHelpedId in question answering
2. change question filtering to reflect deleted questions

Closes # (issue number)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests)
Provide instructions so we can reproduce. 

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-11 03:29 UTC, Ferdinand737 requested changes
I found a bug while testing that creates duplicates.

![image](https://github.com/ubco-db/office-hours/assets/71345367/fa98da6c-0ad3-48a2-be6b-979cc280f180)


Steps to reproduce.

1. **As Student** => Create question
2. **As Student** => Do not click 'satisfied' or 'need faculty help'
3. **As Prof** => Post response to question and mark "verified" and "visible"

2024-03-11 03:29 UTC, Ferdinand737 commented on packages/app/components/Questions/AsyncQuestions/AsyncQuestionForm.tsx
When creating a question the form is populated with previous question. Is this intentional?
Steps to reproduce:

1. **As Student** => Create a new question
2. **As Student** => Click "Post your Question"
3. The form is pre-populated with content from first question

2024-03-11 03:29 UTC, Ferdinand737 commented on packages/app/components/Questions/AsyncQuestions/AsyncQuestionForm.tsx
> -          aiAnswerText: 'AI answer being generated...',
Why did you get rid of this?

2024-03-11 03:29 UTC, Ferdinand737 commented on packages/app/components/Questions/AsyncQuestions/AsyncQuestions.tsx
> +    console.log(questions)
remove this?

2024-03-11 03:29 UTC, Ferdinand737 commented on packages/app/components/Questions/AsyncQuestions/AsyncQuestions.tsx
> +    console.log(displayedQuestions)
remove this?

2024-03-11 03:29 UTC, Ferdinand737 commented on packages/app/components/Questions/AsyncQuestions/StudentQuestionDetailButtons.tsx
> +  // if (question.status !== asyncQuestionStatus.Waiting) {
Remove if not needed

2024-03-11 03:29 UTC, Ferdinand737 commented on packages/app/components/Questions/AsyncQuestions/TAanswerQuestionModal.tsx
> +    console.log(question)
remove this

2024-03-11 03:29 UTC, Ferdinand737 commented on packages/app/components/Questions/AsyncQuestions/TAanswerQuestionModal.tsx
> +          <Switch
I really like these Switches

2024-03-11 03:29 UTC, Ferdinand737 commented on packages/server/src/asyncQuestion/asyncQuestion.entity.ts
I do not see a migration file for this change. 
`yarn migration:generate -n add-verified-to-async`

2024-03-11 03:29 UTC, Ferdinand737 commented on packages/server/src/asyncQuestion/asyncQuestion.controller.ts
> +      // faculties.forEach((professors) => {
Remove this if not needed

2024-03-11 03:29 UTC, Ferdinand737 commented on packages/server/src/asyncQuestion/asyncQuestion.controller.ts
>      return question;
consider using `res.send()`

2024-03-12 03:30 UTC, wskksw commented
The bug with duplicates is found, it turns out that the same question is returned twice both in helpedQuestions and visibleQuestions filtering, I would do a bit more to see what's the best way to filter and fix the bug.

2024-03-17 04:55 UTC, wskksw commented
@Ferdinand737 Have completed requested changes, lmk whether they suffice

2024-03-17 05:22 UTC, AdamFipke commented
While I like the yellow background for when the question still needs attention by the student (i.e. if they're satisfied or not), I **think it should be a white background if the student is satisfied.** I think the background should only be yellow if either:
- the student hasn't yet said responded if they're satisfied/not satisfied
- the question needs attention from the staff (i.e. student not satisfied)

I like the yellow background since it will help bring attention to questions that probably need to be edited (if a professor) or are likely to get updated in the future (if a student) 

![image](https://github.com/ubco-db/office-hours/assets/13655728/9b38517e-d77e-47e7-87a8-6e91e7eb44f7)

2024-03-17 05:26 UTC, AdamFipke commented on packages/app/components/Questions/AsyncQuestions/README.MD
> +Due to the variability of expanded or not, a state in asyncquestions.tsx is maintained to keep track of which cards are expanded or not by storing the question id in an array/variable.
> Due to the variability of expanded or not, a state in asyncquestions.tsx is maintained to keep track of which cards are expanded or not by storing the question id in an array/variable.

This is helpful, I like this kind of documentation that explains why something is done a certain way

2024-03-17 05:31 UTC, AdamFipke approved these changes
I did a little test of it manually, I think it works good.

Though, seeing as how @Ferdinand737 also did a bunch of work on the async questions, I think we should wait to merge this until he approves.

2024-03-17 16:59 UTC, Ferdinand737 commented
Im getting a really strange issue. 
Steps to reproduce:
1. Log in as student and create async question
2. Log in as instructor and go to `http://localhost:3000/course/1/async_question`
3. The page loads forever and does not display the questions browser becomes unresponsive

I tried this with multiple browsers, firefox gave this message.
![image](https://github.com/ubco-db/office-hours/assets/71345367/99db734f-d1aa-42f4-912f-bcc3b1fd3f90)

2024-03-17 19:15 UTC, wskksw commented
I can't reproduce the strange issue you mentioned. Can someone else try it too?

2024-03-17 19:44 UTC, Ferdinand737 commented
> I can't reproduce the strange issue you mentioned. Can someone else try it too?

It works now. I dont know what happened

2024-03-18 00:01 UTC, Ferdinand737 approved these changes

2024-03-18 00:02 UTC, merged