Add/remove ta
ubco-db/office-hours pull request #92
Opened 2024-02-09 00:07 UTC by Ferdinand737

# Description

- Removed override from user_course
- Professors can now edit roles of users in their course

2024-02-13 02:18 UTC, AdamFipke requested changes
Overall I really like what you did here. I like how the searches only update when you hit enter (which is a good idea since a course can have hundreds of students and before i guess it could spam the database). I like the UI, it's clean and simple, and less confusing imo than a "course override."

The one test that failed was the cleanAllQueues one which fails sometimes on its own anyways so it should be fine. 

I pushed like two small changes, one to add a response message when the role change happens and one to make it so the role dropdowns aren't showing the same role (e.g. so you can't switch from Professor to Professor).

I have some requested changes:
- Add a safety mechanism of some kind (perhaps a warning) if you try to demote yourself as a professor (I may or may not have demoted myself to student and couldn't really undo it lol)
- If it's easy, maybe make the lists of users refresh once updated. That way, it's abundently clear to the user that the role change was successful.
 
 Also, idk if this is necessary with typescript, but maybe adding checks & tests if the course, user, or role is invalid might be something to add?

2024-02-29 03:09 UTC, AdamFipke commented
> Thanks for the feedback, I just added the warning popup. It is quite diffucult to make the list update immediatley. I tried doing this but it requires an extensive rework.

Nice work, I like the new warning message. 

For making the lists update, I looked at the code and I now see what you mean lol. I guess one solution would be to add some way for the server to push an update to the tables but yuck. However, I realised that since handleRoleChange can already tell when the role change was succesful or not, that another option is to just somehow tell the other RenderTable components to update themselves when the role change is succesful. So, I went and tried this and, after a little callback function fuckery, this now works (and seems to work pretty well). 

Also, looking through the code, it looks pretty good! Nice work. Left just one comment

2024-02-29 03:10 UTC, AdamFipke requested changes

2024-03-02 21:23 UTC, AdamFipke approved these changes
Looks good, nice work!

2024-03-17 19:27 UTC, wskksw approved these changes

2024-03-17 19:50 UTC, merged